name: Code Coverage/Linting

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
      - uses: actions/checkout@v3
        with:
          ref: master

      - name: Set up Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
      - run: yarn ci

      - name: Run tests
      - run: yarn test --coverage

      - name: Upload code report
      - uses: codecov/codecov-action@v3
      - with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Run lint
      - run: yarn lint
