name: Code Coverage/Linting

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn ci

  test:
    name: Test
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: yarn test --coverage

  lint:
    name: Lint
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: yarn lint
