name: Code Coverage/Linting

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install
        run: yarn install

      - name: Test
        run: yarn test --coverage

      - name: Upload code coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Lint
        run: yarn lint
