name: Code Coverage/Linting

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
      - uses: actions/checkout@v3
        with:
          ref: master

      - name: Set up Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
      - run: yarn ci

  test:
    name: Test
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
      - run: yarn test --coverage

  lint:
    name: Lint
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run lint
      - run: yarn lint
