name: Code Coverage/Linting

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn i
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
        run: yarn test --coverage
        uses: codecov/codecov-action@v2
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
        
  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      run: yarn lint
